In [1]:
import datetime as dt
import data_provider.DataReader as data_provider
import exchange.ExchangeHandler as exchange_provider

In [2]:
start_date = dt.datetime(2023, 1, 1)
end_date = dt.datetime(2023, 9, 15)

In [7]:
data = data_provider.instatiate("stooq").price_data("aapl", start_date, end_date)

In [8]:
data

               Open      High     Low   Close     Volume
Date
2023-09-05  188.280  189.9800  187.61  189.70   45280027
2023-09-01  189.485  189.9200  188.28  189.46   45766503
2023-08-31  187.840  189.1200  187.48  187.87   60794467
2023-08-30  184.940  187.8500  184.74  187.65   60813888
2023-08-29  179.695  184.9000  179.50  184.12   53003948
...             ...       ...     ...     ...        ...
2023-01-09  130.465  133.4100  129.89  130.15   70790813
2023-01-06  126.010  130.2900  124.89  129.62   87754715
2023-01-05  127.130  127.7700  124.76  125.02   80962708
2023-01-04  126.890  128.6557  125.08  126.36   89113633
2023-01-03  130.280  130.9000  124.17  125.07  112117471

[169 rows x 5 columns]

In [11]:
import yfinance as yf

In [13]:
import yfinance as yf
msft = yf.Ticker("dai")
print(msft.info)

{'exchange': 'YHD', 'quoteType': 'MUTUALFUND', 'symbol': 'DAI', 'underlyingSymbol': 'DAI', 'firstTradeDateEpochUtc': 1198852200, 'timeZoneFullName': 'America/New_York', 'timeZoneShortName': 'EDT', 'uuid': '80142798-9346-39bd-af59-e9aec3d85943', 'gmtOffSetMilliseconds': -14400000, 'maxAge': 86400, 'trailingPegRatio': None}

In [16]:
from yahoo_fin.stock_info import get_data

In [33]:
a= get_data("ETH-USD", start_date="09/01/2023", end_date="09/05/2023", index_as_date = True, interval="1wk")

In [34]:
a

,open,high,low,close,adjclose,volume,ticker
2023-08-28,1645.581299,1653.531738,1603.034180,1636.117676,1636.117676,12199979406,ETH-USD
2023-09-04,1635.724731,1645.948364,1610.141235,1633.629395,1633.629395,8305460814,ETH-USD